choco install googlechrome --y
choco install notepadplusplus.install --y
choco install git.install --y
choco install slack --y
choco install vscode --y
choco install tortoisegit --y
choco install autohotkey.install --y
choco install unikey --y
choco install rdcman --y
choco install evernote --y
choco install postman --y
choco install python --y